### ISSUE TITLE
java.util.zip.ZipException: invalid entry compressed size

### ISSUE THREAD

**Issue by kdeng** [rvowles/bathe-plugin#5]
When I try to make a WAR with bathe-plugin under Java 7, it complains the invalid compressed size error.

[INFO] bathe war generation, library offset lib/
[ERROR] Failed to process jar /Users/kdeng/.m2/repository/com/h2database/h2/1.4.187/h2-1.4.187.jar
java.util.zip.ZipException: invalid entry compressed size (expected 4583 but got 4590 bytes)
    at java.util.zip.ZipOutputStream.closeEntry(ZipOutputStream.java:248)
    at java.util.zip.ZipOutputStream.putNextEntry(ZipOutputStream.java:177)
    at java.util.jar.JarOutputStream.putNextEntry(JarOutputStream.java:109)
    at org.springframework.boot.loader.tools.JarWriter.writeEntry(JarWriter.java:184)
    at org.springframework.boot.loader.tools.JarWriter.writeEntries(JarWriter.java:103)
    at org.springframework.boot.loader.tools.JarWriter$writeEntries.call(Unknown Source)
    at com.bluetrainsoftware.maven.bathe.BatheTimeMojo.copyWholeJar(BatheTimeMojo.groovy:314)
    at sun.reflect.GeneratedMethodAccessor41.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
    at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324)
    at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:368)
    at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1016)
    at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:66)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:141)
    at com.bluetrainsoftware.maven.bathe.BatheTimeMojo$_extractOtherLibraries_closure6.doCall(BatheTimeMojo.groovy:213)
    at sun.reflect.GeneratedMethodAccessor40.invoke(Unknown Source)

**Comment by rvowles** [comment]
Which version are you using?

**Comment by kdeng** [comment]
I was using bathe-plugin 2.1 under both java 7 and 8.

**Comment by rvowles** [comment]
So where is your example project?

**Comment by kdeng** [comment]
git@github.com:kdeng/lmz-practice.git
